---
locale: pt
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: "`volume` é uma variável local"
  checked: false
- value: "`volume` é uma variável global"
  checked: true
- value: "`aumentar_volume` é uma função"
  checked: false
- value: "`aumentar_volume` é um procedimento"
  checked: true
- value: "`diminuir_volume` é uma função"
  checked: false
- value: "`diminuir_volume` é um procedimento"
  checked: true
- value: "`e_volume_saudavel` é uma função"
  checked: true
- value: "`e_volume_saudavel` é um procedimento"
  checked: false
- value: "`aumentar_volume` retorna um número"
  checked: false
- value: "`e_volume_saudavel` retorna um número"
  checked: false
- value: "`e_volume_saudavel` retorna um booleano"
  checked: true
name: Vamos diminuir o volume
