---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`volume` é uma variável local"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`volume` é uma variável global"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`aumentar_volume` é uma função"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`aumentar_volume` é um procedimento"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`diminuir_volume` é uma função"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`diminuir_volume` é um procedimento"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`e_volume_saudavel` é uma função"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`e_volume_saudavel` é um procedimento"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`aumentar_volume` retorna um número"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`e_volume_saudavel` retorna um número"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`e_volume_saudavel` retorna um booleano"
  checked: true
name: Vamos diminuir o volume
